version: '3.7'

services:
  opendeck:
    container_name: opendeck
    image: paradajz168/opendeck-dev
    volumes:
      - $PWD:/home/opendeck/OpenDeck
    working_dir: /home/opendeck/OpenDeck
    command: tail -f /dev/null