---
  flash:
    boot-start-page: 0
    app-start-page: 16
    app-boot-jump-offset: 260
    emueeprom:
      factory-page:
        page: 72
      page1:
        page: 136
      page2:
        page: 200
  adc:
    prescaler: 6
    samples: 16