---
  mcu: "stm32f405rg"
  extClockMhz: 8
  usb: true
  uart:
    dinMIDI:
      channel: 2
    touchscreen:
      channel: 5
      components: 64
  i2c:
    display:
      channel: 0
  buttons:
    type: "native"
    extPullups: false
    pins:
    -
      port: "B"
      index: 12
    -
      port: "B"
      index: 14
    -
      port: "C"
      index: 8
    -
      port: "A"
      index: 8
    -
      port: "A"
      index: 14
    -
      port: "C"
      index: 10
    -
      port: "C"
      index: 12
    -
      port: "B"
      index: 3
    -
      port: "B"
      index: 13
    -
      port: "B"
      index: 15
    -
      port: "C"
      index: 9
    -
      port: "A"
      index: 13
    -
      port: "A"
      index: 15
    -
      port: "C"
      index: 11
    -
      port: "D"
      index: 2
    -
      port: "B"
      index: 4
  analog:
    type: "native"
    inputVoltage: "3.3"
    pins:
    -
      port: "A"
      index: 0
    -
      port: "A"
      index: 1
    -
      port: "A"
      index: 2
    -
      port: "A"
      index: 3
    -
      port: "A"
      index: 4
    -
      port: "A"
      index: 5
    -
      port: "A"
      index: 6
    -
      port: "A"
      index: 7
    -
      port: "B"
      index: 0
    -
      port: "B"
      index: 1
    -
      port: "C"
      index: 0
    -
      port: "C"
      index: 1
    -
      port: "C"
      index: 2
    -
      port: "C"
      index: 3
    -
      port: "C"
      index: 4
    -
      port: "C"
      index: 5
  leds:
    external:
      type: "native"
      pins:
      -
        port: "B"
        index: 5
      -
        port: "B"
        index: 8
      -
        port: "B"
        index: 9
      -
        port: "B"
        index: 11
      -
        port: "B"
        index: 2
      -
        port: "C"
        index: 15
      -
        port: "C"
        index: 13
      -
        port: "C"
        index: 10
      -
        port: "C"
        index: 14