---
  mcu: "nrf52840"
  usb: true
  ble: true
  uart:
    dinMIDI:
      pins:
        rx:
          port: "1"
          index: 12
        tx:
          port: "1"
          index: 11
    touchscreen:
      pins:
        rx:
          port: "1"
          index: 12
        tx:
          port: "1"
          index: 11
      components: 64
  i2c:
    display:
      pins:
        sda:
          port: "0"
          index: 4
        scl:
          port: "0"
          index: 5
  buttons:
    type: "native"
    extPullups: false
    pins:
    -
      port: "1"
      index: 15
    -
      port: "1"
      index: 14
  analog:
    type: "native"
    inputVoltage: "3.0"
    pins:
    -
      port: "0"
      index: 2
    -
      port: "0"
      index: 3
    -
      port: "0"
      index: 28
    -
      port: "0"
      index: 29
  leds:
    internal:
      invert: true
      pins:
        usb:
          rx:
            port: "0"
            index: 26
          tx:
            port: "0"
            index: 30
        uart:
          rx:
            port: "0"
            index: 26
          tx:
            port: "0"
            index: 30
        ble:
          rx:
            port: "0"
            index: 26
          tx:
            port: "0"
            index: 30
    external:
      type: "native"
      pins:
      -
        port: "1"
        index: 13